### ISSUE TITLE
Install Corner Culling Source Engine

### ISSUE THREAD

**Issue by soascii** [87andrewh/CornerCullingSourceEngine#7]
Hey bro, i have few questions, i hope you could answer me
Can we install this plugin for a server community in csgo like for admins were they could see the suspects cam?
Its only drop the content of installthis in the server maps ?
Only the owner of the server can do this install for the sv community?

**Comment by soascii** [comment]
Sorry my english bro :)

**Comment by 87andrewh** [comment]
1) Hmm, I'm not sure what you mean. The plugin doesn't break spectator or replay systems, if that's what you're asking.
2) Yes, to install it you will only need to drag the contents of "installthis" into csgo-ds/csgo. Same as any other sourcemod plugin.
3) Anyone with access to the files of the server can install it. They just need to drag and drop the files.
