### ISSUE TITLE
TF2 portability

### ISSUE THREAD

**Issue by sapphonie** [87andrewh/CornerCullingSourceEngine#9]
Hi, TF2 server admin here, and AC geek to boot;

Any way to port this to TF2? Really don't wanna set up a build env and have it not work due to unforseen incompatibility.

Thanks!

**Comment by 87andrewh** [comment]
Hi, I think the code should work in TF2, so the building shouldn't be an issue. However, all the maps data is manually crafted, sooo it would take several hours of work to add each new map.
